name: Build and Release x2t WebAssembly

on:
  push:
    tags:
      - 'v*'  # Trigger on version tags like v1.0.0
  workflow_dispatch:  # Allow manual triggering

jobs:
  build-and-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # Needed for creating releases
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0  # Needed for proper git history handling

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Check Docker version
        run: docker version
        
      - name: Check file permissions
        run: |
          cat embuild.sh
          chmod +x embuild.sh

      - name: Build x2t WebAssembly
        run: |
          mkdir -p build results
          
          # 检查和修复 embuild.sh 文件权限
          echo "修复 embuild.sh 文件权限"
          chmod +x embuild.sh
          
          # 修改 Dockerfile 确保 embuild.sh 有执行权限
          echo "修改 Dockerfile 添加执行权限"
          sed -i 's/COPY embuild.sh \/bin\/embuild.sh/COPY embuild.sh \/bin\/embuild.sh\nRUN chmod +x \/bin\/embuild.sh/' Dockerfile
          
          # 修改 build.sh 以移除不兼容的 --format docker 参数
          echo "修改 build.sh 移除不兼容参数"
          sed -i 's/--format docker //g' build.sh
          chmod +x build.sh
          
          # 执行构建
          ./build.sh
          
          # 如果构建目录存在，显示内容
          ls -la build/ || echo "构建目录不存在或为空"
          
      - name: Set tag name
        id: tag
        run: |
          if [[ $GITHUB_REF == refs/tags/* ]]; then
            echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
          else
            echo "tag=latest-build-$(date +'%Y%m%d-%H%M%S')" >> $GITHUB_OUTPUT
          fi
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: OnlyOffice x2t WebAssembly ${{ steps.tag.outputs.tag }}
          draft: false
          prerelease: false
          files: |
            build/x2t.js
            build/x2t.wasm
            build/x2t.zip
            build/x2t.zip.sha512
          body: |
            ## OnlyOffice x2t WebAssembly Build
            
            This release contains the WebAssembly build of OnlyOffice x2t converter.
            
            ### Files included:
            - x2t.js - JavaScript interface file
            - x2t.wasm - WebAssembly binary
            - x2t.zip - Combined package with JS and WASM files
            - x2t.zip.sha512 - SHA512 hash of the zip file
            
            Built using GitHub Actions on ${{ github.repository }} from commit ${{ github.sha }}
